export const CONSTANTS = {
  ACTIONS: {
    START_GAME: 'START_GAME',
    END_GAME: 'END_GAME',
    RESET: 'RESET',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    ANSWER_QUESTION: 'NSWER_QUESTION',
    NEXT_QUESTION: 'NEXT_QUESTION',
    SUBMIT_WINNER_FORM: 'SUBMIT_WINNER_FORM',
  },
};
